// <auto-generated />
using System;
using AlbumApplication.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlbumApplication.DAL.Migrations
{
    [DbContext(typeof(RecordShopContext))]
    partial class RecordShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminAlbum", b =>
                {
                    b.Property<int>("AdminsId")
                        .HasColumnType("int");

                    b.Property<int>("AlbumsId")
                        .HasColumnType("int");

                    b.HasKey("AdminsId", "AlbumsId");

                    b.HasIndex("AlbumsId");

                    b.ToTable("AdminAlbum");
                });

            modelBuilder.Entity("AlbumApplication.Data.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Password = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("AlbumApplication.Data.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SalesStatu")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Teoman",
                            DiscountRate = 0m,
                            IsDeleted = false,
                            Name = "İki Aşk",
                            Price = 10.99m,
                            ReleaseDate = new DateTime(2006, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalesStatu = true
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Adele",
                            DiscountRate = 0m,
                            IsDeleted = false,
                            Name = "21",
                            Price = 12.99m,
                            ReleaseDate = new DateTime(2011, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalesStatu = true
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Amy Winehouse",
                            DiscountRate = 0.10m,
                            IsDeleted = false,
                            Name = "Back to Black",
                            Price = 9.99m,
                            ReleaseDate = new DateTime(2006, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalesStatu = true
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Nirvana",
                            DiscountRate = 0m,
                            IsDeleted = false,
                            Name = "Nevermind",
                            Price = 8.99m,
                            ReleaseDate = new DateTime(1991, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalesStatu = true
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Pink Floyd",
                            DiscountRate = 0m,
                            IsDeleted = false,
                            Name = "The Dark Side of the Moon",
                            Price = 11.99m,
                            ReleaseDate = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalesStatu = true
                        },
                        new
                        {
                            Id = 6,
                            Artist = "The Beatles",
                            DiscountRate = 0.11m,
                            IsDeleted = false,
                            Name = "Abbey Road",
                            Price = 10.99m,
                            ReleaseDate = new DateTime(1969, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalesStatu = true
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Fleetwood Mac",
                            DiscountRate = 0m,
                            IsDeleted = false,
                            Name = "Rumours",
                            Price = 9.99m,
                            ReleaseDate = new DateTime(1977, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalesStatu = true
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Michael Jackson",
                            DiscountRate = 0m,
                            IsDeleted = false,
                            Name = "Thriller",
                            Price = 12.99m,
                            ReleaseDate = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalesStatu = true
                        },
                        new
                        {
                            Id = 9,
                            Artist = "U2",
                            DiscountRate = 0.15m,
                            IsDeleted = false,
                            Name = "The Joshua Tree",
                            Price = 11.99m,
                            ReleaseDate = new DateTime(1987, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalesStatu = true
                        },
                        new
                        {
                            Id = 10,
                            Artist = "Guns N' Roses",
                            DiscountRate = 0m,
                            IsDeleted = false,
                            Name = "Appetite for Destruction",
                            Price = 10.99m,
                            ReleaseDate = new DateTime(1987, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalesStatu = true
                        });
                });

            modelBuilder.Entity("AdminAlbum", b =>
                {
                    b.HasOne("AlbumApplication.Data.Entities.Admin", null)
                        .WithMany()
                        .HasForeignKey("AdminsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlbumApplication.Data.Entities.Album", null)
                        .WithMany()
                        .HasForeignKey("AlbumsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
